FROM python:3.8-slim

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PIP_INSTALL="python -m pip --no-cache-dir install --upgrade"

RUN apt-get update &&\
    apt-get install -y\
            libgl1-mesa-glx \
            protobuf-compiler \
            libprotoc-dev \
            libb64-0d \
            libglib2.0-0 \
            libgomp1 \
            gcc \
            curl  \
            libturbojpeg0 \
            git &&\
    rm -rf /var/lib/apt/lists/*

COPY src/requirements.txt .
RUN $PIP_INSTALL -r requirements.txt

WORKDIR /app
COPY src/api_trt /app/api_trt
COPY src/entrypoint.sh /app/entrypoint.sh

RUN mkdir -p /models
COPY models/models.json /models/models.json

ENTRYPOINT [ "bash" ]
CMD ["entrypoint.sh"]
